### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by penguincoder** [jmmv/endbasic#61]
Hi jmmv,

I followed your instructions in the README, but I get the following error when using `cargo install endbasic`:

       Compiling endbasic-core v0.5.0
       Compiling endbasic-std v0.5.0
       Compiling endbasic v0.5.0
        Finished release [optimized] target(s) in 15.05s
    error: no binaries are available for install using the selected features

The binary `endbasic` was not dropped into `$HOME/.cargo/bin`. I know I am missing something simple, what can it be?

**Comment by jmmv** [comment]
Looks like I unintentionally broke that workflow as part of recent changes to reshuffle the dependencies on crossterm. I have a fix coming (and a test!) and will cut 0.5.1 right after so that the instructions work again. Thanks for finding this!

**Comment by jmmv** [comment]
Alright. 0.5.1 is out and `cargo install endbasic` should now work as documented.
